Row UDF scalar arguments
dask-contrib/dask-sql pull request #311
Opened 2021-11-11 20:58 UTC by brandon-b-miller

Closes https://github.com/dask-contrib/dask-sql/issues/279

In progress, needs a little code to disambiguate column names that happen to be the same as a constant that is passed

2021-11-15 20:46 UTC, brandon-b-miller commented
This is ready for review - I thought some code might need to be written to disambiguate when one has a column with a name that could also be a constant, like having a column with name `42` and also passing 42 as a constant parameter. But it turns out we can just write `\"42\"` in the query to get the column with that name instead.

2021-11-16 14:06 UTC, ayushdg requested changes
Thanks a lot for the changes @brandon-b-miller !
Couple of minor comments in addition to the changes suggested:
Would it be possible to also update the docstring to include an example with scalar values?

Also I was able to catch the issues below while testing this with udfs that accept multiple column args, since in the single arg case the output would be correct. Might be worth adding that case to the tests as well.

2021-11-16 14:06 UTC, ayushdg commented on dask_sql/datacontainer.py
> +                    df[col.name] = operand
```suggestion
                    df[col.name] = col
```

2021-11-16 14:06 UTC, ayushdg commented on dask_sql/datacontainer.py
> +                    df[col.name] = operand
I'm guessing this section was meant to be outside the loop.

2021-11-16 14:53 UTC, brandon-b-miller commented
Updated! :)

2021-11-16 20:40 UTC, charlesbluca reviewed
Thanks for the work here @brandon-b-miller 🙂 just small nitpicks, the code itself LGTM

2021-11-16 20:40 UTC, charlesbluca commented on tests/integration/test_function.py
> +# Test row UDFs with one args
```suggestion
# Test row UDFs with two args
```

2021-11-16 20:40 UTC, charlesbluca commented on tests/integration/test_function.py
> +# Test row UDFs with one args
```suggestion
# Test row UDFs with one arg
```

2021-11-16 20:46 UTC, ayushdg approved these changes
One small suggestion otherwise lgtm!

2021-11-16 20:46 UTC, ayushdg commented on dask_sql/datacontainer.py
> +                df = column_args[0].to_frame()
```suggestion
            df = column_args[0].to_frame()
```

2021-11-16 22:06 UTC, charlesbluca approved these changes
LGTM; thanks for the work @brandon-b-miller 😄

2021-11-16 22:09 UTC, merged