Enable DataFusion CBO and introduce DaskSqlOptimizer
dask-contrib/dask-sql pull request #558
Opened 2022-05-31 16:34 UTC by jdye64

Closes: #476

2022-06-01 19:13 UTC, ayushdg requested changes
Rust changes lgtm! Minor suggestions on the python side

2022-06-01 19:13 UTC, ayushdg commented on dask_sql/context.py
> +            rel, select_fields, _ = self._get_ral(sql, config_options)
We can avoid passing this explicitly and use the `dask_config.get` directly within `_get_ral`. 

It has the added advantage of being able to use config options set in a dask yaml or explicitly set in the context that's not explicitly passed in here

2022-06-01 19:13 UTC, ayushdg commented on tests/integration/test_join.py
> +@pytest.mark.skip(
While some of the optimization work in ongoing, we can maybe create an issue for these cases where the optimized plan isn't handled where the issue can track the optimized and non optimized version of the plans.

2022-06-01 20:02 UTC, charlesbluca commented on dask_sql/utils.py
> +    def __init__(self, sql, exception_string):
Is there a reason we need to pass on `sql` to this class initialization?

2022-06-02 16:41 UTC, charlesbluca reviewed
Small nitpick around the config option itself:

2022-06-02 16:41 UTC, charlesbluca commented on dask_sql/context.py
> +                rel = nonOptimizedRel
Nitpicky, but would it be more direct to make this config option `optimize` and have it do the opposite of what it's doing now?

```suggestion
        if dask_config.get("sql.optimize"):
            try:
                rel = self.context.optimize_relational_algebra(nonOptimizedRel)
            except DFOptimizationException as oe:
                rel = nonOptimizedRel
        else:
            rel = nonOptimizedRel
```

2022-06-02 16:41 UTC, charlesbluca commented on dask_sql/sql-schema.yaml
> +      skip_optimize:
```suggestion
      optimize:
```

2022-06-02 16:41 UTC, charlesbluca commented on dask_sql/sql.yaml
> +  skip_optimize: True
```suggestion
  optimize: False
```

2022-06-03 12:48 UTC, jdye64 commented
Confused why all the tests in this PR pass locally but not in CI?? Trying to figure that out.

Locally:
```65 passed, 329 skipped, 1 xfailed, 200 warnings in 27.66s```

2022-06-07 16:20 UTC, charlesbluca approved these changes

2022-06-07 16:47 UTC, ayushdg approved these changes

2022-06-07 16:51 UTC, merged