Datafusion upstream merge
dask-contrib/dask-sql pull request #576
Opened 2022-06-13 19:06 UTC by jdye64

Merge upstream/main into the datafusion-sql-planner branch after the recent release.

2022-06-13 19:59 UTC, ayushdg requested changes
Given that some of the changes here are ones that were added for timestampdiff. It might make sense to exclude all the changes for now that were made in #495 apart from tests or include everything and remove the parts that are not relevant later.

2022-06-13 19:59 UTC, ayushdg commented on dask_sql/mappings.py
> +    if pd.api.types.is_integer_dtype(expected_type):
Some of these changes were added to incorporate the `timestampdiff` related operations

2022-06-13 19:59 UTC, ayushdg commented on dask_sql/physical/rex/core/call.py
> +        if isinstance(result, (datetime.timedelta, np.timedelta64)):
Same

2022-06-13 19:59 UTC, ayushdg commented on dask_sql/physical/rex/core/call.py
> +        "reinterpret": CastOperation(),
Same

2022-06-13 20:56 UTC, jdye64 commented
@ayushdg Does the last commit address what you were talking about?

2022-06-13 23:22 UTC, ayushdg commented
> @ayushdg Does the last commit address what you were talking about?

It does but I now realize it's still missing some of the old logic that was updated for timestampdiff, eg places like [this]( https://github.com/dask-contrib/dask-sql/pull/495/files#diff-d3cd58a1b69c1ecccbefe8b23cd8e3c78cfc005841dd6711a094e75f388a289eL290).


To ensure that some of these changes don't slip through, I'm actually considering just including all the changes made to #495 and then removing bit that are not needed in a followup. Apologies if that increases the amount work needed on this pr.

2022-06-17 16:57 UTC, ayushdg approved these changes
Some changes from #581 also made it in. But changes lgtm!

2022-06-17 17:01 UTC, merged