Uncomment more test_model pytests
dask-contrib/dask-sql pull request #728
Opened 2022-08-26 18:05 UTC by ChrisJar

2022-08-30 14:20 UTC, jdye64 commented
@ChrisJar this PR is marked as draft but seems to have working tests? Is it ready for review?

2022-08-30 14:35 UTC, ChrisJar commented
There's a few more things on the way

2022-08-30 23:04 UTC, jdye64 requested changes
Lots of good stuff here @ChrisJar couple of small requests but looks good!

2022-08-30 23:04 UTC, jdye64 commented on dask_planner/src/sql/logical/export_model.rs
> +    fn _str_from_expr(expression: SqlParserExpr) -> String {
Could you move this whole function to `dask_planner/src/sql/parser_utils.rs`? Seems handy for others to use as well.

2022-08-31 21:58 UTC, jdye64 approved these changes
LGTM

2022-08-31 21:58 UTC, merged