Replace `dask_ml.wrappers.ParallelPostFit` with custom `ParallelPostFit` class
dask-contrib/dask-sql pull request #832
Opened 2022-09-30 22:13 UTC by sarahyurick

As part of our initiative to move away from Dask-ML, I've migrated some code from Dask-ML into Dask-SQL to support ParallelPostFit.

2022-09-30 22:17 UTC, sarahyurick commented on dask_sql/physical/rel/custom/wrappers.py
> +                pass
Dask-ML has a utility function called `get_scorer` that we still need to replicate. The toy example I was working with passed without it, so I'm mostly just curious to see if any of our tests fail without it :)

2022-09-30 22:37 UTC, sarahyurick commented on dask_sql/physical/rel/custom/wrappers.py
> +    Output execution time of a function to the given logger level
Do we care about having this function?

2022-10-05 16:57 UTC, sarahyurick commented
Let me know if you think any tests from Dask-ML's `tests/test_parallel_post_fit.py` or from https://github.com/dask/dask-ml/pull/912 should be added.

2022-10-11 22:00 UTC, VibhuJawa commented on tests/integration/test_model.py
> +# TODO - many ML tests fail on clusters without sklearn - can we avoid this?
@ayushdg , What will be the recommended way to test something that has a install dependency ?

2022-10-12 19:54 UTC, sarahyurick commented on tests/integration/test_model.py
> +@skip_if_external_scheduler
@charlesbluca Wanted to ask you about this since we have it for several of the `test_model` pytests

2022-10-14 16:08 UTC, sarahyurick commented on tests/integration/test_model.py
> +@skip_if_external_scheduler
Opened an issue for this here: https://github.com/dask-contrib/dask-sql/issues/861

2022-10-18 16:35 UTC, charlesbluca commented on dask_sql/physical/rel/custom/wrappers.py
> +import sklearn.metrics
Should we wrap these in a `try`/`except` similar to what we were doing for dask-ml since scikit-learn isn't a core dependency?

2022-10-24 17:54 UTC, VibhuJawa approved these changes
Small Change, looks good other-wise

2022-10-24 17:56 UTC, VibhuJawa requested changes
Requesed Small change, Looks good other-wise.

2022-10-24 17:56 UTC, VibhuJawa commented on dask_sql/physical/rel/custom/wrappers.py
> +                pass
Can you actually raise an error here instead of passing. 
```suggestion
               raise NotImplementedError("Relevant error message")
```

2022-10-24 18:10 UTC, VibhuJawa approved these changes
LGTM

2022-10-24 18:16 UTC, ayushdg approved these changes
Thanks for this @sarahyurick. Changes generally look good to me. 

In addition to some of the integration tests added here which check the interaction of sql with our wrappers, it might make sense (in a followup) to also add unit tests that independently test the wrappers functionality outside of sql and make sure things are working as expected. 

We can probably adapt the tests from https://github.com/dask/dask-ml/blob/94e52613fc87abd4ef8c97510539ded1303ae6f4/tests/test_parallel_post_fit.py and add it to the `tests/unit` section

2022-10-24 18:16 UTC, ayushdg commented on dask_sql/physical/rel/custom/wrappers.py
> +    raise ValueError("sklearn must be installed")
Minor nit: I would prefer the raised error here to be an `importError` as well. 
Looking through the codebase it seems like the original errors were also `valueErrors` but `importError` might be cleaner

2022-10-24 18:19 UTC, charlesbluca approved these changes

2022-10-24 20:14 UTC, merged